export const STRINGS = {
  pricePool: 'Price pool',
  selectMonth: 'SelectMonth',
  ticketBooth: 'Ticketbooth',
  selectBuyin: 'Select buy-in',
  yourTickets: 'Your Tickets',
  ticketAmount: '- Amount ',
  ticketEntryDate: '- Entry date ',
  ticketWalletAddress: '- Wallet ',
  eth: ' eth, ',
  craffpp: 'Craffpp',
  home: 'Home',
  play: 'Play',
  controller: 'Controller',
  howDoesItWork: 'How does it work',
  termsAndConditions: 'Terms and conditions',
  oceanCleanup: 'Ocean cleanup',
  fristPlace: 'First place',
  secondPlace: 'Second place',
  thirdPlace: 'Third place',
  orderSummary: 'Order summary',
  selectedPool: 'Selected pool ',
  buyinAmount: 'Buy-in amount',
  ticketCount: 'Ticket count',
  agreeTerms: 'I agree to terms and conditions',
  winnersDraw: 'Winners Draw',
  selectWinners: 'Select winners',
  sendWinners: 'Send winners',
  position: 'Position',
  address: 'Address',
  actions: 'Actions',
  totals: 'Totals',
  totalTickets: 'Total Tickets',
  totalEthereum: 'Total Ethereum',
  homeHeader: 'Crypto raffle for the planet and the people',
  filteredTotals: 'Filtered Totals',
  connectWallet: 'Connect Wallet',
}