export const STRINGS = {
  pricePool: 'Price pool',
  selectMonth: 'SelectMonth',
  ticketBooth: 'Ticketbooth',
  selectBuyin: 'Select buy-in',
  yourTickets: 'Your Tickets',
  ticketAmount: '- Amount ',
  ticketEntryDate: '- Entry date ',
  ticketWalletAddress: '- Wallet ',
  eth: ' eth, ',
  craffpp: 'Craffpp',
  home: 'Home',
  donate: 'Donate',
  controller: 'Controller',
  howDoesItWork: 'How does it work',
  termsAndConditions: 'Terms and conditions',
  oceanCleanup: 'Ocean cleanup',
  fristPlace: 'First place',
  secondPlace: 'Second place',
  thirdPlace: 'Third place',
  orderSummary: 'Order summary',
  selectedPool: 'Selected pool ',
  buyinAmount: 'Buy-in amount',
  ticketCount: 'Ticket count',
  agreeTerms: 'I agree to terms and conditions',
  winnersDraw: 'Winners Draw',
  selectWinners: 'Select winners',
  sendWinners: 'Send winners',
  position: 'Position',
  address: 'Address',
  actions: 'Actions',
  totals: 'Totals',
  totalTickets: 'Total Tickets',
  totalEthereum: 'Total Ethereum',
  homeHeader: 'Crypto raffle for the planet and the people',
  filteredTotals: 'Filtered Totals',
  connectWallet: 'Connect Wallet',
  connectMetamask: 'Connect your Metamask wallet and go to Donate tab',
  selectBuyinMonth: 'Select the buy-in and month of the raffle you want to participate. Each buy-in represents a set of winners (First, second and third place). You will be able to see the cumulative ETH total on every raffle per Buy-in amount. Then click Buy ticket and confirm transaction.',
  raffles: 'Raffles are decided the 28th of every month. The winner addresses are selected randomly. One address can win multiple prices in a sigle raffle. Meaning a single address can win all first, second and third position prices having bought at  least 3 tickets. The more tickets the more chances.',
  transfers: 'Once a raffle is decided, the winning addresses will appear in the price pool board. Winner addresses receive their corresponding winning ETH amounts in no more than 24 hours.',
  priceDistribution: 'Each paid buy-in in distributed in the raffle the following way; Ocean and coastline cleanup 16%,  First place 40%, Second place 25% and Third place 15%. Remaining 4% for development team and platform maintainance.',
  panamaBio: 'Panamá, is a country full of biodiversity, it is in fact well known for hosting one of the most wide varieties of plants and animal species in both land and sea. Only in Panamá, 220 species of freshwater fish and 1,157 species of marine fish have been identified. Panamá is also home to 3.4% of the world\'s amphibian species.',
  panamaCrisis: 'The list could go on and on but. What is important here is, that all this coastline, and rivers are currently in danger because of the huge amount of trash comming from different rivers all around the country, specially the ones closer to the city.',
  panamaContribution: 'For every pool we create, 16% of the profits will go to the reenforcement of efforts to take out as much trash as possible outside of Panamá coastlines. This includes, donating to local ONG\'s specialliced in the matter and the collection and recycling of the plastic.'
}